export const ADD_MENU = "NAV_MENU/ADD_MENU";
export const SET_USER = "LOGIN_USER/SET_USER";
export const SET_CHARACTER = "LOGIN_USER/DETAIL/SET_CHARACTER";
export const SET_SELECTOR = "NAV_MENU/SET_SELECTOR";
export const SET_ROOT_CLASS = "CODE/SET_ROOT_CLASS";
export const SET_CLASS = "CODE/SET_CLASS";
export const SET_CONTENTS_NAME = "NAV_MENU/SET_CONTENTS_NAME";
